name: Publish NuGet

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:

  publish-nuget:
    name: Publish NuGet
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:

      - name: Read Metadata
        run: |
          echo "Version: ${{ inputs.version }}"

      - name: Download NuGet Artifact
        uses: actions/download-artifact@v3
        with:
          name: NuGet-${{runner.os}}-v${{ inputs.version }}
          path: artifacts

      - name: Read Directory
        run: |
          ls -1 artifacts

      - name: Push To GitHub Packages
        run: >
          dotnet nuget push "artifacts/*"
          --skip-duplicate
          --source "https://nuget.pkg.github.com/StudioLE/index.json"
          --symbol-source "https://nuget.pkg.github.com/StudioLE/index.json"
          --api-key "${{ secrets.GITHUB_TOKEN }}"
