name: CI/CD

on:
  push:
  pull_request:
    branches:
      - alpha

jobs:

  analysis:
    name: Analysis
    uses: ./.github/workflows/01-analysis.yml
    secrets: inherit

  build-and-test-ubuntu:
    name: Ubuntu
    needs: analysis
    uses: ./.github/workflows/02-build-and-test.yml
    with:
      solution: Geometrician.Libraries.sln
      os: ubuntu-latest
      version: ${{ needs.analysis.outputs.version }}
    secrets: inherit

  build-and-test-windows:
    name: Windows
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs: analysis
    uses: ./.github/workflows/02-build-and-test.yml
    with:
      solution: Geometrician.Libraries.sln
      os: windows-latest
      version: ${{ needs.analysis.outputs.version }}
    secrets: inherit

  publish-nuget:
    name: Publish NuGet
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs:
      - analysis
      - build-and-test-ubuntu
    uses: ./.github/workflows/03-publish-nuget.yml
    with:
      version: ${{ needs.analysis.outputs.version }}
    secrets: inherit

  publish-docs:
    name: Publish Docs
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs:
      - analysis
    uses: ./.github/workflows/04-publish-docs.yml
    with:
      solution: Geometrician.Libraries.sln
      version: ${{ needs.analysis.outputs.version }}
    secrets: inherit

  build-app:
    name: Build WebAssembly App
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs:
      - analysis
    uses: ./.github/workflows/05-build-webassembly-app.yml
    with:
      solution: Geometrician.Cascade.WebAssembly/src/Geometrician.Cascade.WebAssembly.csproj
      version: ${{ needs.analysis.outputs.version }}
    secrets: inherit

  publish-app:
    name: Publish WebAssembly App
    if: ${{ contains(fromJSON('["refs/heads/main", "refs/heads/alpha", "refs/heads/beta"]'), github.ref) }}
    needs:
      - analysis
      - build-and-test-ubuntu
      - build-app
    uses: ./.github/workflows/06-publish-webassembly-app.yml
    with:
      version: ${{ needs.analysis.outputs.version }}
    secrets: inherit
